#!/usr/bin/env python

from __future__ import print_function
import os
import sys
import json
import argparse
import subprocess
from sys import version_info


DEVNULL = open(os.devnull, 'w')

def get_args():
    parser = argparse.ArgumentParser("serviced-set-version")
    parser.add_argument("service", metavar="SERVICE", help="Name of the service whose version you wish to modify.")
    parser.add_argument("version", metavar="VERSION", help="New version of the service you want to set.")
    return parser.parse_args()

def main():
    args = get_args()
    print("Looking up service %s" % args.service, file=sys.stderr)
    try:
        svc_json = subprocess.check_output(["serviced", "service", "list", args.service])
        parsed = json.loads(svc_json)
    except subprocess.CalledProcessError as e:
        sys.exit(e.returncode)
    except ValueError:
        sys.exit(1)
    old_version = parsed.get("Version")
    print("Service %s has version %s" % (args.service, old_version), file=sys.stderr)
    parsed["Version"] = args.version
    print("Set new version %s" % args.version, file=sys.stderr)
    print("Saving new version of %s" % args.service, file=sys.stderr)
    try:
        proc = subprocess.Popen(["serviced", "service", "edit", args.service], stdin=subprocess.PIPE, stdout=DEVNULL)
        dump = json.dumps(parsed)
        proc.communicate(dump if version_info[0] < 3 else dump.encode("utf-8"))
    except subprocess.CalledProcessError as e:
        sys.exit(e.returncode)


if __name__ == "__main__":
    main()
